Update CMap Tips
iTwin/bis-schemas pull request #97
Opened 2022-06-01 14:35 UTC by caseymullen

Added a GIF for changing arrowheads style and fixed broken links

2022-06-01 15:03 UTC, karolis-zukauskas approved these changes

2022-06-01 15:04 UTC, diegoalexdiaz submitted a review, later dismissed

2022-06-01 15:07 UTC, ColinKerr requested changes
Please do not put a 2 MB binary file into the git repo

2022-06-03 13:50 UTC, caseymullen commented
> Please do not put a 2 MB binary file into the git repo

I was able to get it down to 500k using Camtasia. OK? Also fixed some broken links.

2022-06-03 18:58 UTC, ColinKerr approved these changes

2022-06-03 18:58 UTC, merged